SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, precio * 0.93 FROM producto;
SELECT nombre, precio AS 'euros' , truncate(precio * 0.93,2) AS 'dolares'  FROM producto;
SELECT ucase(nombre), precio FROM producto;
SELECT lcase(nombre), precio FROM producto;
SELECT nombre, ucase(substring(nombre, 1, 2)) FROM fabricante;
SELECT  nombre, round(precio) AS 'precio' FROM producto;
SELECT nombre, precio AS 'con decimales', truncate(precio, 0) AS 'sin decimales' FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT codigo_fabricante FROM producto group by codigo_fabricante;
SELECT nombre FROM fabricante order by nombre asc;
SELECT nombre FROM fabricante order by nombre desc;
SELECT nombre, precio FROM producto order by nombre asc, precio desc;
SELECT * FROM fabricante limit 5;
SELECT * FROM fabricante limit 3,2;
SELECT nombre, precio FROM producto order by precio asc limit 1;
SELECT nombre, precio FROM producto order by precio desc limit 1;
SELECT nombre, codigo_fabricante FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante);
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante) order by f.nombre asc;
SELECT p.codigo, p.nombre, f.codigo, f.nombre FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante);
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON (f.codigo = p.codigo) order by p.precio  asc limit 1;
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON (f.codigo = p.codigo) order by p.precio  desc limit 1;
SELECT * FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre = 'lenovo';
SELECT * FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre = 'crucial' and p.precio < 200;
SELECT * FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre = 'asus' or f.nombre = 'Hewlett-Packard' or f.nombre = 'Seagate';
SELECT * FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre in ('asus', 'Hewlett-Packard', 'Seagate');
SELECT * FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre like '%e';
SELECT * FROM producto p JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE f.nombre like '%w%';
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON (f.codigo = p.codigo) WHERE p.precio > 180 ORDER BY p.precio desc, p.nombre asc;
SELECT f.codigo, f.nombre FROM fabricante f JOIN producto p ON (p.codigo_fabricante = f.codigo) group by f.codigo;
SELECT f.nombre as Fabricante, p.nombre as producto FROM producto p right JOIN fabricante f ON (p.codigo_fabricante = f.codigo) ORDER BY f.codigo;
SELECT f.nombre as Fabricante, p.nombre as producto FROM producto p right JOIN fabricante f ON (p.codigo_fabricante = f.codigo) WHERE p.nombre is null;
SELECT p.nombre, f.nombre FROM producto p LEFT JOIN fabricante f ON (f.codigo = p.codigo_fabricante) WHERE f.nombre = 'lenovo'; 	
SELECT * FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante) WHERE precio = (SELECT MAX(p.precio) FROM producto JOIN fabricante ON (f.codigo = p.codigo_fabricante) WHERE f.nombre = 'Lenovo');
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante) WHERE f.nombre = 'Lenovo' ORDER BY p.precio desc limit 1;
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante) WHERE f.nombre = 'Hewlett-Packard' ORDER BY p.precio asc limit 1;
SELECT * FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante) WHERE p.precio >= (SELECT MAX(precio) FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante) WHERE f.nombre = 'Lenovo');
SELECT * FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante) WHERE p.precio >= (SELECT AVG(precio) FROM producto p JOIN fabricante f ON (f.codigo = p.codigo_fabricante) WHERE f.nombre = 'Asus');  
